config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup',  to: 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  #get 'followings' => 'users#followings'
  #get 'followers' => 'users#followers'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  
  #メンバールーティング
  resources :users do
    member do
      get 'following'
      get 'follower'
      get 'bookmarking'
      #get 'bookmarker'
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
    if logged_in?
    # Micropost.new(user_id: current_user.id)と同じ
    # has_many :microposts(user.rb)で生成される"build"を推奨
      @micropost = current_user.microposts.build
      
      #降順（ページネーション付き）
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page]).per(7)
      #昇順（ページネーション付き）
      # @feed_items = current_user.feed_items.includes(:user).order(:created_at).page(params[:page]).per(7)
    end
  end
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      
      <%= link_to t('follow_label'), following_user_path(current_user) %>
      (<%= current_user.following_users.count %>)
      <%= link_to t('follower_label'), follower_user_path(current_user) %>
      (<%= current_user.follower_users.count %>)
      <%= link_to t('bookmark_label'), bookmarking_user_path(current_user) %>
      (<%= current_user.bookmarking_posts.count %>)
      
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    
    <!-- タイムライン表示 -->
    <div class="col-md-8">
      <h3><%= current_user.name %>さんのタイムライン</h3>
      
      <!-- ページネーション表示 -->
      <%= page_entries_info @feed_items, entry_name: "投稿" %>
      <%= render 'shared/feed' %>
      <%= paginate @feed_items %>
      
    </div>
    
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t('welcome') %></h1>
    <hr />
    <%= link_to t('sinup_now'), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>