config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup',  to: 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  #get 'followings' => 'users#followings'
  #get 'followers' => 'users#followers'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  
  #メンバールーティング
  resources :users do
    member do
      get 'following'
      get 'follower'
      get 'bookmarking'
      #get 'bookmarker'
    end
  end

end

app/views/layouts/_header.html(旧).erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t('title'), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('header_home'), root_path %></li>
        <li><%= link_to t('header_help'), '#' %></li>
        <% if logged_in? %>
          <li><%= link_to t('header_users'), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=t('header_account')%> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('header_profile'), current_user %></li>
              <li><%= link_to t('header_setting'), '#' %></li>
              <li><%= link_to t('header_editing'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('header_logout'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('header_login'), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    
    <!--ロゴの表示-->
    <%= link_to t('title'), root_path, id:"logo" %>
    
    <!--トグルボタンの設置（スマホの場合）-->
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-content">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  
  <div id="nav-content" class="collapse navbar-collapse">
    <!--リンクのリスト メニューリスト-->
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t('header_home'), root_path %></li>
      <li><%= link_to t('header_help'), '#' %></li>
      
      <% if logged_in? %>
        <li><%= link_to t('header_users'), users_path %></li>
        <!--ドロップダウン化するliタグ-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=t('header_account')%> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('header_profile'), current_user %></li>
            <li><%= link_to t('header_setting'), '#' %></li>
            <li><%= link_to t('header_editing'), edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to t('header_logout'), logout_path, method: "delete" %></li>
          </ul>
        </li>
      <% else %>
          <li><%= link_to t('header_login'), login_path %></li>
      <% end %>
        
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>マイクロポスト</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |message_type, message| %> <!-- ここから -->
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> <!-- ここまで追加 -->
    
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application_smart_phone.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>マイクロポスト</title>
    <%= stylesheet_link_tag 'smart_phone/application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |message_type, message| %> <!-- ここから -->
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> <!-- ここまで追加 -->
    
      <%= yield %>
    </div>
  </body>
</html>